[global]
    tds version = 7.4
    client charset = UTF-8
    text size = 64512
    encryption = request

[shaka_dw]
    host = host.docker.internal
    port = 1433
    tds version = 7.4
    client charset = UTF-8
    encryption = request
