[global]
repo1-type=posix
repo1-path=/var/lib/pgbackrest
repo1-retention-full=5
repo1-retention-archive-type=full
process-max=4
log-level-console=info
log-level-file=detail

[shaka_db]
pg1-path=/var/lib/postgresql/data
pg1-user=shaka
