{
    'name': 'BI',
    'version': '19.0.1.0.0',
    'category': 'Shaka ERP',
    'summary': 'Placeholder module for Shaka business-intelligence features',
    'description': """
BI
==
Scaffold for future Shaka business-intelligence screens. It currently ships
only the default views and demo data generated by ``odoo-bin scaffold``.
""",
    'author': 'ShakaERP',
    'maintainer': 'ShakaERP',
    'website': 'https://shakasystem.com',
    'license': 'LGPL-3',
    'icon': '/bi/static/description/icon.svg',
    'depends': ['base'],
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
