from . import telegram_bot
from . import telegram_message
from . import telegram_template
from . import res_partner
from . import res_users
from . import res_users_settings
from . import res_config_settings
from . import mail_thread
from . import discuss_channel
from . import ir_actions_server
from . import calendar_alarm
from . import calendar_alarm_manager
from . import calendar_event
