{
    "name": "POS Employee Free Items (2 per day + 2FA)",
    "version": "19.0.1.0.0",
    "summary": "Allow each POS employee to claim two free items per day. Items are chosen by the admin. Claim requires a TOTP code generated by an authenticator app on the employee phone.",
    "category": "Point of Sale",
    "depends": [
        "point_of_sale",
        "auth_totp",
        "hr"
    ],
    "data": [
        "security/pos_free_item_security.xml",
        "security/ir.model.access.csv",
        "views/free_item_catalog_views.xml",
        "views/employee_free_allowance_views.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        "views/pos_screen_views.xml",
        "data/pos_free_item_demo.xml"
    ],
    "assets": {
        "point_of_sale.assets": [
            "pos_employee_free_items/static/src/js/pos_free_items.js"
        ]
    },
    "license": "LGPL-3",
    "installable": True,
    "application": False,
    "auto_install": False
}