{
    "name": "POS Employee Free Items (2 per day + 2FA)",
    "version": "19.0.1.0.0",
    "summary": "Allow each POS employee to claim two free items per day. Items are chosen by the admin. Claim requires a TOTP code generated by an authenticator app on the employee phone.",
    "category": "Point of Sale",
    "depends": [
        "point_of_sale",
        "auth_totp",
        "hr"
    ],
    "data": [
        "security/pos_free_item_security.xml",
        "security/ir.model.access.csv",
        "views/free_item_catalog_views.xml",
        "views/employee_free_allowance_views.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        # REMOVED: "templates/pos_screen_templates.xml"
        "data/pos_free_item_demo.xml"
    ],
    "assets": {
        # Note: In modern Odoo, _assets_pos is the standard bundle for POS UI
        "point_of_sale._assets_pos": [
            "static/src/js/pos_free_items.js",
            "templates/pos_screen_templates.xml"
        ]
    },
    "author": "ShakaERP",
    "license": "LGPL-3",
    "installable": True,
    "application": False,
    "auto_install": False
}
